### ISSUE TITLE
Badge on news

### ISSUE THREAD

**Issue by olajoh1** [malmostad/intranet-dashboard#64]
What are the possiblilities for us to work with badges for "New" or/and "Important" on news?

See DI for inspiration:

![ny_nyhet](https://cloud.githubusercontent.com/assets/6176181/11087721/ea9f0dba-885c-11e5-9aec-e65357f800db.PNG)

**Comment by pbrotherton** [comment]
What would qualify as "New" in a case like this - new entries since the user last logged in or new entries within a certain time period (eg. 24 hours)? Marking an entry as "Important" on external feeds is not possible but on internal feeds it should be possible without having to make any changes to the current structure of the XML

**Comment by magnivar** [comment]
Closed in favor of Sharepoint
