### ISSUE TITLE
Allow the contacts_editor role to edit personal profiles

### ISSUE THREAD

**Issue by jesperbylund** [malmostad/intranet-dashboard#65]
Buttons for profile and picture has gone missing from the role "Kontaktboksredaktör".

![knappar](https://cloud.githubusercontent.com/assets/3509721/15283451/07e3f3c8-1b4b-11e6-91e4-ad8358cd17ba.png)

**Comment by martent** [comment]
Just to avoid deep search for regression bugs; this has never been allowed for kontaktboksredaktörer, they are only allowed to edit functional contacts by design.

So the edit action must be added to the whitelist for kontaktboksredaktörer, both the buttons and the allowance to save the data from the form.

**Comment by pbrotherton** [comment]
Deployed in staging

**Comment by martent** [comment]
Probably deployed in prod too.

**Comment by magnivar** [comment]
Edit profile work but cannot change photo even though button exists

**Comment by magnivar** [comment]
Change photo is fixed
